tests: Adapt to pygobject 3.55.0
After upgrading pygobject from 3.54.5 to 3.55.2, Python tests
expecting a process failure on setting an immutable
(G_PARAM_CONSTRUCT_ONLY) property started to fail like this:

    Traceback (most recent call last):
      File "/home/test/libmodulemd-devel/redhat-linux-build/../modulemd/tests/ModulemdTests/defaults.py", line 114, in test_module_name
	self.assertProcessFailure(_set_module_name_to_none, defs)
	~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/test/libmodulemd-devel/modulemd/tests/ModulemdTests/base.py", line 60, in assertProcessFailure
	callable(*args)
	~~~~~~~~^^^^^^^
      File "/home/test/libmodulemd-devel/redhat-linux-build/../modulemd/tests/ModulemdTests/defaults.py", line 43, in _set_module_name_to_none
	defs.props.module_name = None
	^^^^^^^^^^^^^^^^^^^^^^
    TypeError: property 'module-name' can only be set in constructor

The cause was that pygobject-3.55.0 started to raise a Python
TypeError exception instead of calling Glib functions which would fail
on its own depending on Glib warning fatality and Glib version. An example:

    cat /tmp/test.py
    #!/usr/bin/python3

    import gi
    gi.require_version("Modulemd", "2.0")
    from gi.repository import Modulemd

    object = Modulemd.Defaults.new(Modulemd.DefaultsVersionEnum.LATEST, "foo")
    object.props.module_name = "bar"

Before:

    $ /tmp/test.py
    /tmp/test.py:8: Warning: g_object_set_is_valid_property: construct property "module-name" for object 'ModulemdDefaultsV1' can't be set after construction
      object.props.module_name = "bar"

After:

    $ /tmp/test.py
    Traceback (most recent call last):
      File "/tmp/test.py", line 8, in <module>
	object.props.module_name = "bar"
	^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: property 'module-name' can only be set in constructor

That was an intentional change in pygobject
3b6e4804de4f26cfb9472666f18f44ac731d874c commit (gi: Factor out
pygi_set_property_gvalue_from_property_info). Probably an
optimization.

This patch adjusts the tests to pass if TypeError exception is raised
regardless of Glib warning fatality.

Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2440570